name: flutter_template
description: Template for Flutter apps
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0

  # Testing
  bloc_test: ^9.0.3
  mockito: ^5.2.0

  # Networking
  retrofit: ^3.0.1+1

  # Routing
  go_router: ^5.0.2

  # Data
  freezed: ^2.0.5
  json_serializable: ^6.3.1

  # Localization
  easy_localization: ^3.0.1

  # Misc
  equatable: ^2.0.3
  path_provider: ^2.0.10
  google_fonts: ^3.0.1
  very_good_analysis: ^3.1.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  retrofit_generator: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/
